import { reset, seed } from 'drizzle-seed'
import { db, sql } from './connection.ts'
import { questions } from './schema/questions.ts'
import { rooms } from './schema/rooms.ts'

// Exclude audioChunks from seed because it contains vector embeddings
// that cannot be generated by drizzle-seed
const seedSchema = { rooms, questions }

await reset(db, seedSchema)
await seed(db, seedSchema).refine((f) => {
  return {
    rooms: {
      count: 5,
      columns: {
        name: f.companyName(),
        description: f.loremIpsum(),
      },
    },
    questions: {
      count: 20,
    },
  }
})

await sql.end()

// biome-ignore lint/suspicious/noConsole: only used in dev
console.log('Database seeded')
